modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/MCTeamPotato/Better-End-Potato-Edition/issues"
[[mods]]
modId="betterendforge"
version="${file.jarVersion}"
displayName="Better End Potato Edition"
displayURL="https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked"
credits="Beethoven92, Vemerion, SomeoneElse, All the artistic rights and credits, except for Forge-specific portions of code, go to the original authors of the BetterEnd mod for the Fabric mod loader"
authors="Team Potato"
description='''
This mod adds new content to the end dimension that vastly improves and expands your end game.
'''